# Generated by Django 6.0.2 on 2026-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_comment_rating_phoneimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.CharField(blank=True, help_text='e.g., 4000 mAh', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.CharField(blank=True, help_text='e.g., 8GB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='screen_size',
            field=models.CharField(blank=True, help_text='e.g., 6.1 inches', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='storage_capacity',
            field=models.CharField(blank=True, help_text='e.g., 256GB', max_length=50, null=True),
        ),
    ]
