# Generated by Django 6.0.2 on 2026-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of items in stock'),
        ),
    ]
